name: Publish Docker image
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  pull-docker:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull Docker Image
      run: |
          echo Running docker image
          cd docker
          ls -ltr
          ./run.sh
      
